name: dcat
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Ben <ben399399@naver.com>

environment:
  sdk: '>=2.2.0 <3.0.0'
  

dependencies:
  cli_util: '^0.2.0'
  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
